// Generated by CoffeeScript 1.8.0
(function() {
  
  var BubbleChart, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BubbleChart = (function() {
    function BubbleChart(data, container, width, height) {
      this.hide_details = __bind(this.hide_details, this);
      this.show_details = __bind(this.show_details, this);
      this.hide_years = __bind(this.hide_years, this);
      this.display_years = __bind(this.display_years, this);
      this.move_towards_year = __bind(this.move_towards_year, this);
      this.display_by_group = __bind(this.display_by_group, this);
      this.start = __bind(this.start, this);
      this.render = __bind(this.render, this);
      this.create_nodes = __bind(this.create_nodes, this);
      var max_amount;
      this.container = container;
      this.data = data;
      this.width = width;
      this.height = height;
      this.tooltip = CustomTooltip("startup_funding_tooltip", 240);
      this.center = {
        x: 100 + this.width / 2 ,
        y: this.height / 2
      };
      this.off_screen = {
        x: this.width + 300,
        y: this.height / 2
      };
      this.layout_gravity = -0.01;
      this.damper = 0.1;
      this.vis = null;
      this.nodes = [];
      this.force = null;
      this.circles = null;
      this.fill_color = d3.scale.ordinal()
        .domain(["Angel Round", "Seed Round", "Series A", "Series B", "Series C", "Series D", "Series E", "Series F", "Series G", "Private Equity"])
        .range(["#72AEE3","#72AEE3", "#9DC6EB", "#C7DFF4", "#FCD800", "#FC9C00", "#FC4300",  "#FC4300", "#FC4300", "#6D992F"]);
      max_amount = d3.max(this.data, function(d) {
        
        return parseInt(d.amount);
      });

      
      
      this.radius_scale = d3.scale.pow().exponent(0.5).domain([0, max_amount]).range([4, 65]);
      this.create_nodes();
      this.render();
    }

    BubbleChart.prototype.create_nodes = function() {
      var self = this;
      
      this.data.forEach(function(d) {
          var node;
          if(parseInt(d.amount) <= 0) {
            return;
          } 
          
          node = {
            id: d.id,
            radius: self.radius_scale(parseInt(d.amount)),
            value: d.amount,
            name: d.name,
            org: d.vc_list,
            group: d.stage,
            year: d.year,
            x: Math.random() * 900,
            y: Math.random() * 800
          };
          

          return self.nodes.push(node);
      });

      return this.nodes.sort(function(a, b) {
        return b.value - a.value;
      });
    };

    BubbleChart.prototype.render = function() {
      var self = this;
      
      this.vis = d3.select(this.container).append("svg").attr("width", "100%").attr("height", this.height).attr("id", "svg_vis");
      
      this.circles = this.vis.selectAll("circle").data(this.nodes, function(d) {
        return d.id;
      });
      
      this.circles.enter()
      .append("circle")
      .each(function (d) {
        var stroke_color = d3.rgb(self.fill_color(d.group)).darker(),
            fill_color = self.fill_color(d.group);
        
        d3.select(this).attr({
          r: 0,
          fill: fill_color,
          "fill-opacity": 0.8,
          "stroke-width": 1.5,
          stroke: stroke_color,
          id: "bubble_" + d.id

        });  
      })
      .on("mouseover", function(d, i) {
        var counter = 0
        d.org.forEach(function(name){
          counter = counter + 1;
          d3.select("text#vc-title-" + counter).text(name);  
          return true;
        });
        
        return self.show_details(d, i, this);
      })
      .on("mouseout", function(d, i) {
        for(var i = 1; i < 7; i++){
          d3.select("text#vc-title-" + i).text(""); 
        }
        console.log("out" + this)
        return self.hide_details(d, i, this);
      });
      
      // Total investment
      this.vis.append("text")
        .attr("x", 20)
        .attr("y",500)
        .text("$0")
        .attr("class","system-font sum")
        .attr("id", "money")
        .attr("fill", "black");  

      // Total investment
      this.vis.append("text")
        .attr("x", 900)
        .attr("y",500)
        .text("$0")
        .attr("class","system-font sum")
        .attr("id", "quantity")
        .attr("fill", "black"); 

      return this.circles.transition().duration(2000).attr("r", function(d) {
        return d.radius;
      });
    
    };
    
    
    BubbleChart.prototype.charge = function(d) {
      return -Math.pow(d.radius, 2.0) / 7 ;
    };

    BubbleChart.prototype.start = function() {
      return this.force = d3.layout.force().nodes(this.nodes).size([this.width, this.height]);
    };

    BubbleChart.prototype.display_by_group = function(list) {
      var self = this;
      
      var dic =  { 
        "seed": ["Angel Round", "Seed Round"],
        "series-a": ["Series A"],
        "series-b": ["Series B", "Series C"],
        "series-d": ["Series D", "Series E", "Series F", "Series G"],
        "private": ["Private Equity"]
      }
      
      var group = [];
      
      list.forEach(function (item) {
        group = group.concat(dic[item]);
        return group;
      });

      this.force.gravity(this.layout_gravity)
        .charge(this.charge)
        .friction(0.9)
        .on("tick", function(e) {
          return self.circles
            .each(self.move_towards_target(
                e.alpha,
                function(d) { 
                  
                  
                  if(group.indexOf(d.group) >= 0){
                    return self.center;   
                  } else {
                    return self.off_screen;  
                  }
                  
                })
            )
            .attr("cx", function(d) {
              return d.x;
            })
            .attr("cy", function(d) {
              return d.y;
            });
      });

      var sum = 0;
      var count = 0;
      this.nodes.forEach( function (d) {
        
        if(group.indexOf(d.group) >= 0){
          count = count + 1;
          sum = sum + parseInt(d.value);
        } 
      });
      
      d3.select("#money").text('$' + addScale(sum));
      d3.select("#quantity").text('#' + addCommas(count));
      return this.force.start();

    };

    BubbleChart.prototype.move_towards_target = function(alpha, target) {
      var self = this;
      
      return function(d) {
          d.x = d.x + (target(d).x - d.x) * (self.damper + 0.02) * alpha * 1.1;
          return d.y = d.y + (target(d).y - d.y) * (self.damper + 0.02) * alpha * 1.1;
      };
      
    };

    BubbleChart.prototype.show_details = function(data, i, element) {
      var content;
      d3.select(element).attr("stroke", "black");
      content = "<span class=\"name\">Title:</span><span class=\"value\"> " + data.name + "</span><br/>";
      content += "<span class=\"name\">Amount:</span><span class=\"value\"> $" + (addScale(data.value)) +  "</span><br/>";
      content += "<span class=\"name\">Last Round:</span><span class=\"value\"> " + data.group + "</span><br/>";
      content += "<span class=\"name\">Year:</span><span class=\"value\"> " + data.year + "</span>";

      return this.tooltip.showTooltip(content, d3.event);
    };

    BubbleChart.prototype.hide_details = function(data, i, element) {
      d3.select(element).attr("stroke", (function(_this) {
        return function(d) {
          return d3.rgb(_this.fill_color(d.group)).darker();
        };
      })(this));
      return this.tooltip.hideTooltip();
    };

    
    return BubbleChart;

  })();
  
  var DataLabels = (function() {
        
        // Constructor        
        function DataLabels(data, container, width, height) {
            // Holdes the data
            this.data = data;

            // Width of label
            this.labelWidth = width;
            this.labelHeight = height;
            
            this.container = container;
            this.vis = null;
        }
    
        DataLabels.prototype.createNode = function () {

        };


        DataLabels.prototype.render = function () {
            this.vis = d3.select(this.container + " svg");
            
            if(this.vis === null || this.vis === 'undefined') {
                console.log("Vis is not loaded");
            }

            var startPointY = 100;
                
                

            //this.data = [{ id: 1, name: 'ddd'},{ id: 2, name: '2ddd'}];
            
            var self = this;
            
            var defs = this.vis.append("defs");

            var filter = defs.append("filter")
                .attr("id", "glow");
            
            // Title
            this.vis.append("text")
              .attr("x", 20)
              .attr("y",startPointY)
              .text("INVESTORS LIST:")
              .attr("class","title system-font")
              .attr("fill", "black");   

            var lablesContainer = this.vis
                            .selectAll("g")
                            .data(this.data, function(d) {
                                return d.id;
                            })
                            .enter().append("g")
                            .attr("class","vc lable");
            
            var currentY = startPointY + 20,
                counter = 0;
            
            lablesContainer.append("title")
                .text(function(d) { return d.name; });

            lablesContainer.append("text")
                .attr("x", 25)
                .each(function (d){
                    counter = counter + 1;
                    title_class_pos = "odd";
                    if( counter % 2  == 0) {
                      title_class_pos = "even";
                    }
                    var tempY = currentY;
                    currentY= currentY + 32;
                    
                    d3.select(this).attr({
                        y: currentY,
                        "class":  "investor "+ title_class_pos +" system-font",
                        id: "vc-title-" + counter
                    }).text("");    
                });
                
        };

        return DataLabels;
  }());

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  

  $(function() {
    var chart, render_vis, render_lbl;
    var active_groups = ["seed", "series-a", "series-b", "series-d", "private"];
    var inactive_groups = [];
    chart = null;
    lables = null;
    
    render_lbl = function (json) {
        
        labels = new DataLabels(json, "#vis", 150, 40);
        return labels.render();
    }

    render_vis = function (csv) {
      chart = new BubbleChart(csv, "#vis", 1040, 600);
      
      chart.start();
      return chart.display_by_group(active_groups);
    };

    root.display_group = (function(_this) {
      return function(list) {
        return chart.display_by_group(list);
      };
    })(this);
    
    root.toggle_view = (function(_this) {
      return function(view_type) {
        var active_pos = active_groups.indexOf(view_type)
        
        if (active_pos >= 0) {
          inactive_groups.push(view_type);
          active_groups.splice(active_pos, 1);
        } else {
          inactive_groups.splice(inactive_groups.indexOf(view_type), 1);
          active_groups.push(view_type);  
        }

        return root.display_group(active_groups);
        
      };
    })(this);

    // Render visualisation
    //var v = d3.csv("data/test.csv", render_vis);
    var v = d3.json("data/test.json", function(data) {

      render_vis(data);
      // Render label
      d3.json("data/labels.json", render_lbl);

    });
    
    


    return v;
  });

}).call(this);
